### ISSUE TITLE
(3.3.4) FormBuilderDateTimePicker ignoring initialDate

### ISSUE THREAD

**Issue by abhinavc** [danvick/flutter_form_builder#108]
Hi Danvick, 

Noticed a possible breaking change. 

Passing `initialDate: DateTime.tryParse("20000101")`, for example, in the constructor has no effect. The date picker still open at current date. 

And if one passes a `lastDate` that is before today, then one gets an 
`!initialDate.isAfter(lastDate)` assertion error from within `date_picker.dart`

The problem seems to be here in `form_builder_date_time_picker.dart`
```dart
Future<DateTime> _showDatePicker(
     ....
      return showDatePicker(
          context: context,
          ....
          initialDate: currentValue ?? DateTime.now(),
          firstDate: widget.firstDate ?? DateTime(1900),
          lastDate: widget.lastDate ?? DateTime(2100));
  }
```
I think `initialDate: (currentValue ?? widget.initialDate) ?? DateTime.now()` is what's required. But you can confirm.

Thanks 
Abhinav.

**Comment by danvick** [comment]
Thank you for bringing this to our attention.

**Comment by userone912** [comment]
Hi,
The initialValue also not working in FormBuilderDateTimePicker. The value set in initialValue i.e {'date':DateTime.utc(2010,1,1)} were successfully assigned to the attribute (it is not null) but not printed in the field, it just blank.

**Comment by andyd1** [comment]
Looks like the culprit is that the value of the text editing controller is not being set on intiState.

Adding the following got me back up and running:

In initState(), right after 
    _textFieldController = widget.controller ?? TextEditingController();

    _widget.initialValue == null ? "" :_
    **widget.format == null ? DateFormat("EEEE, MMMM d, yyyy 'at' h:mma").format(
        widget.initialValue) :
    widget.format.format(widget.initialValue));**

I'm sure there is a more elegant way to do this - also, I have a check box in my app to show or hide the date, that logic seems to be not working at the moment.

**Comment by abhinavc** [comment]
This bug has come sometime after `3.0.1`. Hence I am hoping it gets fixed here itself.

**Comment by danvick** [comment]
Hi @abhinavc,
Kindly confirm that this issue is fixed as of `v3.4.0`. 
Feel free to reopen the issue if not.

**Comment by abhinavc** [comment]
Hi Danvick, 
Tried 3.4.1 and it seems the issue still remains.
`firstDate` is honored. `lastDate` is also honored, though specifying one can lead to an assertion 
error because `initialDate` still seems to be set to today's date.
