### ISSUE TITLE
readOnly is not working in FormBuilderDateTimePicker

### ISSUE THREAD

**Issue by shashikantshaale** [danvick/flutter_form_builder#179]
Even after setting readOnly to true in FormBuilderDateTimePicker, user can change the date.

here's my code

```
FormBuilderDateTimePicker(
                  readOnly: true,
                  attribute: 'dob',
                  firstDate: DateTime(1850),
                  initialDate: DateTime.now().subtract(Duration(days: 365 * 6)),
                  lastDate: DateTime.now().subtract(Duration(days: 365 * 5)),
                  inputType: InputType.date,
                  resetIcon: Icon(Icons.close),
                  initialDatePickerMode: DatePickerMode.day,
                  format: DateFormat("MMM d, yyyy "),
                  decoration: InputDecoration(
                    labelText: 'Date of Birth',
                  ),
                ),
```

Version using _**flutter_form_builder: ^3.6.1**_

**Comment by danvick** [comment]
Hi @shashikantshaale,
Thanks fo bringing this to my attention

**Comment by danvick** [comment]
Fixed in v3.7.0. Feel free to reopen on case of any more feedback.

**Comment by shashikantdurge** [comment]
This bug still exists.
Changing **_readOnly_** of _FormBuilder_  does not change **_readOnly_** of _FormBuilderDateTimePicker_

**Comment by shashikantdurge** [comment]
@danvick Can you reopen this issue

**Comment by shashikantshaale** [comment]
That was very quick. Super

**Comment by danvick** [comment]
I've just released a hotfix on pub. Kindly check and confirm if the problem is fixed

**Comment by shashikantshaale** [comment]
Yeah it seems fixed!
