### ISSUE TITLE
 The non-abstract class 'ChipsInputState' is missing implementations v3.7.2 [Latest]

### ISSUE THREAD

**Issue by rdcoder33** [danvick/flutter_form_builder#215]
I can't run my flutter app. I am not even using chips input in my forms.

`flutter_form_builder: ^3.7.2 `

Error:
```
Waiting for another flutter command to release the startup lock...
Launching lib\main.dart on RMX1801 in debug mode...
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

Compiler message:
../../../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_chips_input-1.6.1/lib/src/chips_input.dart:62:7: Error: The non-abstract class 'ChipsInputState' is missing implementations for these members:
 - TextInputClient.currentTextEditingValue
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class ChipsInputState<T> extends State<ChipsInput<T>>
      ^^^^^^^^^^^^^^^
../../../flutter/packages/flutter/lib/src/services/text_input.dart:757:24: Context: 'TextInputClient.currentTextEditingValue' is defined here.
  TextEditingValue get currentTextEditingValue;
                       ^^^^^^^^^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.
* Where:
Script 'C:\Users\Dell\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 801
* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\Users\Dell\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org

BUILD FAILED in 14s
Gradle task assembleDebug failed with exit code 1
Exited (sigterm)
```

**Comment by partlyhuman** [comment]
+1 same here... Issue is open on its own repo: https://github.com/danvick/flutter_chips_input/issues/27
Hot-patching by adding this to `chips_input.dart` will at least let you compile - warning, not tested at all.
```
@override
TextEditingValue get currentTextEditingValue => _value;
```

**Comment by sgalway00** [comment]
I am seeing the same problem.  I've tried hot patch with no luck.

**Comment by joseangeljimenez** [comment]
@sgalway00 It worked for me. However, note you have to patch chips_input.dart (not text_input.dart)

**Comment by danvick** [comment]
This issue is fixed in v3.7.3

**Comment by JCKodel** [comment]
It's still an issue with v3.8.2 and Flutter 1.18.0-5.0.pre.37:

```
Error: The non-abstract class 'ChipsInputState' is missing implementations for these members:
 - TextInputClient.showAutocorrectionPromptRect
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class ChipsInputState<T> extends State<ChipsInput<T>>
      ^^^^^^^^^^^^^^^
/C:/Flutter/packages/flutter/lib/src/services/text_input.dart:764:8: Context: 'TextInputClient.showAutocorrectionPromptRect' is defined here.
  void showAutocorrectionPromptRect(int start, int end);
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by Cretezy** [comment]
To fix this, add this as a dependency: `flutter_chips_input: ^1.9.0-dev.1`
