### ISSUE TITLE
FormBuilderTextField throws "Null check operator used on a null value" while passing FocusNode

### ISSUE THREAD

**Issue by nishitdixit** [danvick/flutter_form_builder#901]
I'm using FormBuilderTextField to take the phone number input with a predefined focus node because I want to shift the focus to the custom OTP field on submit.
everything is working fine but when I click on FormBuilderTextField it throws the following exception.
![image](https://user-images.githubusercontent.com/69981929/139386262-387e3d64-5171-4376-a1a1-71f8cdcecd73.png)

I think it's because the FormBuilderTextField internally uses FormBuilderField, wherein, the method  "FormBuilderFieldState._touchedHandler" has marked focus node as mandatory.

**Comment by ahmednfwela** [comment]
also solved by https://github.com/danvick/flutter_form_builder/pull/876

**Comment by nishitdixit** [comment]
waiting for the release

**Comment by leidig54** [comment]
Can this be expedited? Getting large numbers of crashlytics issues coming through in production. Non-fatal but still not pretty.

**Comment by Ethras** [comment]
any updates on this?

**Comment by WilliamCunhaCardoso** [comment]
Guys it seems it was solved by https://github.com/danvick/flutter_form_builder/pull/876. If Still happens on latest form builder version please contact us.
